### PR TITLE
Add OAuth config and rework URL config

### PR DESCRIPTION
**Pull request by drewsilcock**
This adds support for configuring the Swagger UI OAuth2 integration, as per docs here: https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/.

This also slightly reworks the Swagger specification JSON document location configuration. The default value is `nil` instead of `doc.json` (this is to make it more clear what the configuration parameter is for and to make it work with the additional field in the config). This fixes the link to the Swagger spec when the path is local on the Swagger UI page (just below the "Base Path").

### CODE REVIEW

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@drewsilcock, Would you mind fixing the conflicts so we can go forward with it.

**Comment by jaesung9507** [comment]
When will this branch be merge into master?

**Comment by drewsilcock** [comment]
Hi @ubogdan thanks for your patience, I've resolved the merge conflicts now.

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
@drewsilcock Thanks for your contribution.

**Pull request merged**
