### PR TITLE
Update echo to avoid jwt-go vulnerability.

### PR DESCRIPTION
**Pull request by YutoUrakami**
**Describe the PR**
Since jwt-go has been reported to be vulnerable, we need to migrate to golang-jwt. Therefore, I have updated the version of echo.

### CODE REVIEW

**Comment by ubogdan** [comment]
Until the build passes, we can't merge it.

**Comment by YutoUrakami** [comment]
@ubogdan 
With echo migrated from jwt-go to golang-jwt, it seems that golang 1.14 cannot be supported because the version of golang.org/x/net is also increased. It seems to me that there is no need to support 1.14 with the vulnerability, what do you think?

If you want to continue to support golang 1.14, please close this PR. Only update echo in my repository that I forked here.

**Comment by ubogdan** [comment]
@YutoUrakami We shouldn't drop two versions of GO just like that. 
I'm aware of the JWT package vulnerability. I'm still wondering why do we need to upgrade the swagger-echo dependency hence we are not using the JWT part?

**Comment by YutoUrakami** [comment]
@ubogdan 
Even though echo-swagger does not use JWT, applications that use echo-swagger may use it.

go.sum doesn't have an easy to read dependency description like, for example, Gemfile.lock, and we have to find out what modules depend on jwt-go. Even using GitHub's dependency graph, the dependencies are not easy to read, and this is why This is a disadvantage for echo-swagger users, isn't it?

> Next time, please open an issue to discuss the implementation in advance so you won't waste your time writing code that may be useless or will suffer plenty of changes.

Yes. You're right. I'll be careful next time.

**Comment by ubogdan** [comment]
@YutoUrakami, it looks like we are not on the same page. 

There is an indirect dependency caused by echo-swagger, but this doesn't you can't use the fixed version.

I've tested with go1.13.15 and the
```cmd
go get github.com/golang-jwt/jwt@v3.2.0

swag init
```

file:main.go
```
package main

import (
	"log"

	"github.com/golang-jwt/jwt"
	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"
	echoSwagger "github.com/swaggo/echo-swagger"
	_ "github.com/ubogdan/echo-example/docs" // docs is generated by Swag CLI, you have to import it.
)

type jwtCustomClaims struct {
	Name  string `json:"name"`
	Admin bool   `json:"admin"`
	jwt.StandardClaims
}

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host petstore.swagger.io
// @BasePath /v2
func main() {
	e := echo.New()

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	r := e.Group("/api")

	// Configure middleware with the custom claims type
	config := middleware.JWTConfig{
		Claims:     &jwtCustomClaims{},
		SigningKey: []byte("secret"),
	}
	r.Use(middleware.JWTWithConfig(config))

	err := e.Start(":1323")
	if err != nil {
		log.Fatalf("Failed to start server: %v", err)
	}
}
```

file: go.mod
```
module github.com/ubogdan/echo-example

go 1.13

require (
	github.com/golang-jwt/jwt v3.2.0+incompatible
	github.com/labstack/echo/v4 v4.4.0
	github.com/labstack/gommon v0.3.1 // indirect
	github.com/swaggo/echo-swagger v1.1.4
	github.com/swaggo/swag v1.7.0
	golang.org/x/crypto v0.0.0-20210817164053-32db794688a5 // indirect
	golang.org/x/net v0.0.0-20210913180222-943fd674d43e // indirect
	golang.org/x/text v0.3.7 // indirect
)
```

Conclusion. There is no real reason to drop go1.13 and go1.14 . 

We will drop them incrementally, as we started on swag package,  so our users will have enough time to update the pipelines.

Thanks,
Bogdan

**Comment by YutoUrakami** [comment]
@ubogdan Yes, I don't think we are really talking about the same thing.

I wanted to remove jwt-go from go.sum, so requires [echo over v4.5.0](https://github.com/labstack/echo/releases/tag/v4.5.0).
 But your sample code requires echo v4.4.0.

I'll make sure to use the repository I forked.
I hope that this repository will be updated someday.

**Comment by ubogdan** [comment]
We will update as soon as we will drop go1.14 support. 

For now, we took a step and removed go1.13 from swag and his swagger-ui HTTP handlers.

**Pull request closed without merging**
